# Generated by Django 5.0.1 on 2025-12-11 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_random', models.BooleanField(default=False, help_text='Si activé, pioche aléatoirement dans toutes les paires actives')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_media', models.FileField(upload_to='pairs/real/')),
                ('ai_media', models.FileField(upload_to='pairs/ai/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], default='image', max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='medium', max_length=10)),
                ('hint', models.TextField(blank=True, help_text='Explication affichée après la réponse')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_pairs', to='game.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('media_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_stats', to='game.mediapair')),
            ],
            options={
                'verbose_name_plural': 'Global stats',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('pseudo', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('streak_max', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('time_total_ms', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_sessions', to='game.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('media_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mediapair')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.quiz')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('quiz', 'media_pair')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='pairs',
            field=models.ManyToManyField(blank=True, related_name='quizzes', through='game.QuizPair', to='game.mediapair'),
        ),
        migrations.CreateModel(
            name='GameAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField()),
                ('order', models.PositiveIntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gamesession')),
                ('media_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_answers', to='game.mediapair')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('session', 'order')},
            },
        ),
    ]
