# Generated by Django 5.0.1 on 2025-12-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapair',
            name='audio_media',
            field=models.FileField(blank=True, null=True, upload_to='pairs/audio/'),
        ),
        migrations.AddField(
            model_name='mediapair',
            name='is_real',
            field=models.BooleanField(blank=True, help_text='Pour audio: True si réel, False si IA', null=True),
        ),
        migrations.AlterField(
            model_name='mediapair',
            name='ai_media',
            field=models.FileField(blank=True, null=True, upload_to='pairs/ai/'),
        ),
        migrations.AlterField(
            model_name='mediapair',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo'), ('audio', 'Audio')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediapair',
            name='real_media',
            field=models.FileField(blank=True, null=True, upload_to='pairs/real/'),
        ),
    ]
