# Generated by Django 5.0.1 on 2025-12-15 09:40

import apps.game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_mediapair_audio_media_mediapair_is_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediapair',
            name='ai_media',
            field=models.FileField(blank=True, null=True, upload_to=apps.game.models.get_upload_path_ai),
        ),
        migrations.AlterField(
            model_name='mediapair',
            name='audio_media',
            field=models.FileField(blank=True, null=True, upload_to=apps.game.models.get_upload_path_audio),
        ),
        migrations.AlterField(
            model_name='mediapair',
            name='real_media',
            field=models.FileField(blank=True, null=True, upload_to=apps.game.models.get_upload_path_real),
        ),
    ]
