# Generated by Django 5.0.1 on 2025-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_change_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='audience_type',
            field=models.CharField(choices=[('school', 'Scolaire'), ('public', 'Grand Public')], default='public', help_text="Type d'audience: scolaire ou grand public", max_length=10),
        ),
    ]
