# Generated by Django 5.0.1 on 2025-12-18 13:40

import apps.game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_audience_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='La citation à deviner')),
                ('hint', models.CharField(blank=True, help_text='Indice optionnel pour aider le joueur', max_length=200)),
                ('author_name', models.CharField(help_text="Nom de l'auteur de la citation", max_length=100)),
                ('author_image', models.ImageField(help_text="Photo de l'auteur", upload_to=apps.game.models.get_upload_path_celebrity)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le quiz")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Citation secrète',
                'verbose_name_plural': 'Citations secrètes',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
