# Generated by Django 5.0.1 on 2026-01-05 13:30

import apps.game.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_secret_quote_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=apps.game.models.generate_room_code, help_text='Code unique de la room (6 caractères)', max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('showing_answer', 'Révélation'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('current_pair_index', models.IntegerField(default=0, help_text='Index de la question actuelle')),
                ('ai_positions', models.JSONField(blank=True, default=dict, help_text="Position de l'IA pour chaque paire (pair_id: 'left'|'right')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pairs', models.ManyToManyField(blank=True, help_text='Paires de médias pour cette room', related_name='multiplayer_rooms', to='game.mediapair')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplayer_rooms', to='game.quiz')),
            ],
            options={
                'verbose_name': 'Room Multiplayer',
                'verbose_name_plural': 'Rooms Multiplayer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(help_text='Pseudo du joueur', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('session_token', models.UUIDField(default=uuid.uuid4, help_text='Token unique pour la reconnexion', unique=True)),
                ('channel_name', models.CharField(blank=True, help_text='Nom du channel WebSocket actuel', max_length=255)),
                ('is_connected', models.BooleanField(default=True, help_text='Indique si le joueur est actuellement connecté')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.multiplayerroom')),
            ],
            options={
                'verbose_name': 'Joueur Multiplayer',
                'verbose_name_plural': 'Joueurs Multiplayer',
                'ordering': ['-score', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(help_text="Choix du joueur: 'left', 'right', 'real', 'ai'", max_length=10)),
                ('is_correct', models.BooleanField()),
                ('points_earned', models.IntegerField(default=0)),
                ('response_time_ms', models.IntegerField(help_text='Temps de réponse en millisecondes')),
                ('answer_order', models.IntegerField(default=0, help_text='Ordre de réponse (1er, 2ème, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_answers', to='game.mediapair')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.multiplayerplayer')),
            ],
            options={
                'verbose_name': 'Réponse Multiplayer',
                'verbose_name_plural': 'Réponses Multiplayer',
                'ordering': ['answer_order'],
                'unique_together': {('player', 'media_pair')},
            },
        ),
    ]
