# Generated by Django 5.0.1 on 2025-12-19 08:29

import apps.game.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_secret_quote_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=apps.game.models.generate_room_code, help_text='Code unique à 6 caractères pour rejoindre la room', max_length=6, unique=True)),
                ('host_ip', models.CharField(blank=True, help_text="Adresse IP locale de l'hôte", max_length=45)),
                ('current_pair_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'En attente'), ('playing', 'En cours'), ('showing_answer', 'Affichage réponse'), ('finished', 'Terminé')], default='waiting', max_length=20)),
                ('ai_positions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pairs', models.ManyToManyField(blank=True, related_name='multiplayer_rooms', to='game.mediapair')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multiplayer_rooms', to='game.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MultiplayerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('is_connected', models.BooleanField(default=True)),
                ('channel_name', models.CharField(blank=True, help_text='WebSocket channel name for this player', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.multiplayerroom')),
            ],
            options={
                'ordering': ['-score', 'joined_at'],
                'unique_together': {('room', 'pseudo')},
            },
        ),
        migrations.CreateModel(
            name='MultiplayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField()),
                ('response_time_ms', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('answer_order', models.IntegerField(default=0, help_text='Order in which this answer was received (for bonus calculation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplayer_answers', to='game.mediapair')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.multiplayerplayer')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('player', 'media_pair')},
            },
        ),
    ]
