# Generated by Django 5.0.1 on 2026-01-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_multiplayerroom_multiplayerplayer_multiplayeranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='total_pairs',
            field=models.IntegerField(default=0, help_text='Nombre total de paires dans cette session'),
        ),
    ]
