# Generated by Django 5.0.1 on 2026-01-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_add_total_pairs_to_game_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='pairs',
        ),
        migrations.RemoveField(
            model_name='quizpair',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='multiplayerroom',
            name='quiz',
        ),
        migrations.AlterUniqueTogether(
            name='quizpair',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='quizpair',
            name='media_pair',
        ),
        migrations.DeleteModel(
            name='SecretQuote',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizPair',
        ),
    ]
