# Generated by Django 5.0.1 on 2026-01-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_add_total_pairs_to_game_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplayerroom',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='QuizPair',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
