# Generated by Django 5.0.1 on 2026-01-06 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_multiplayerroom_quiz_remove_gamesession_quiz_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretQuote',
        ),
    ]
